"""empty message

Revision ID: 4242971a78f7
Revises: 947b0d86e831
Create Date: 2022-02-20 17:12:12.701823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4242971a78f7'
down_revision = '947b0d86e831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('category', sa.String(), server_default='command', nullable=False))
    op.add_column('settings', sa.Column('category_position', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'category_position')
    op.drop_column('settings', 'category')
    # ### end Alembic commands ###
