"""empty message

Revision ID: 947b0d86e831
Revises: 
Create Date: 2022-02-19 17:23:48.091218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947b0d86e831'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groupme_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('is_woman', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    op.drop_table('groupme_users')
    # ### end Alembic commands ###
